// Generated by quickshell/scripts/m3-from-wallpaper.py -- do not edit by hand.
// Source: /home/nekoconn/.config/hypr/wallpapers/wallpaper1.webp
// Seed:   #7f63b3  (hue 303deg, chroma 46)
// Derived by: @material/material-color-utilities, SchemeTonalSpot
pragma Singleton
import Quickshell
import QtQuick

Singleton {
    readonly property string wallpaper: "/home/nekoconn/.config/hypr/wallpapers/wallpaper1.webp"
    readonly property color seed: "#7f63b3"
    readonly property bool initialIsDark: true

    readonly property var m3Dark: ({
        primary: "#d3bbfd",
        onPrimary: "#39265c",
        primaryContainer: "#503c74",
        onPrimaryContainer: "#ebdcff",
        inversePrimary: "#68548d",
        secondary: "#cdc2db",
        onSecondary: "#342d40",
        secondaryContainer: "#4b4358",
        onSecondaryContainer: "#eadef8",
        tertiary: "#f1b7c4",
        onTertiary: "#4a252f",
        tertiaryContainer: "#643b46",
        onTertiaryContainer: "#ffd9e1",
        error: "#ffb4ab",
        onError: "#690005",
        errorContainer: "#93000a",
        onErrorContainer: "#ffdad6",
        background: "#151218",
        onBackground: "#e7e0e8",
        surface: "#151218",
        onSurface: "#e7e0e8",
        surfaceDim: "#151218",
        surfaceBright: "#3b383e",
        surfaceContainerLowest: "#0f0d13",
        surfaceContainerLow: "#1d1b20",
        surfaceContainer: "#211f24",
        surfaceContainerHigh: "#2c292f",
        surfaceContainerHighest: "#37343a",
        inverseSurface: "#e7e0e8",
        inverseOnSurface: "#322f35",
        shadow: "#000000",
        scrim: "#000000",
        surfaceVariant: "#49454e",
        onSurfaceVariant: "#cbc4cf",
        outline: "#948f99",
        outlineVariant: "#49454e",
    })

    readonly property var m3Light: ({
        primary: "#68548d",
        onPrimary: "#ffffff",
        primaryContainer: "#ebdcff",
        onPrimaryContainer: "#503c74",
        inversePrimary: "#d3bbfd",
        secondary: "#635b70",
        onSecondary: "#ffffff",
        secondaryContainer: "#eadef8",
        onSecondaryContainer: "#4b4358",
        tertiary: "#7f525d",
        onTertiary: "#ffffff",
        tertiaryContainer: "#ffd9e1",
        onTertiaryContainer: "#643b46",
        error: "#ba1a1a",
        onError: "#ffffff",
        errorContainer: "#ffdad6",
        onErrorContainer: "#93000a",
        background: "#fef7ff",
        onBackground: "#1d1b20",
        surface: "#fef7ff",
        onSurface: "#1d1b20",
        surfaceDim: "#ded8e0",
        surfaceBright: "#fef7ff",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#f8f1fa",
        surfaceContainer: "#f2ecf4",
        surfaceContainerHigh: "#ede6ee",
        surfaceContainerHighest: "#e7e0e8",
        inverseSurface: "#322f35",
        inverseOnSurface: "#f5eff7",
        shadow: "#000000",
        scrim: "#000000",
        surfaceVariant: "#e7e0eb",
        onSurfaceVariant: "#49454e",
        outline: "#7a757f",
        outlineVariant: "#cbc4cf",
    })

}
