// Generated by hypr/scripts/m3-from-wallpaper.py -- do not edit by hand.
// Source: /home/nekoconn/.config/hypr/wallpapers/wallpaper2.png
// Seed:   #eb3264  (hue 10deg, chroma 87)
// Derived by: @material/material-color-utilities, SchemeTonalSpot
pragma Singleton
import Quickshell
import QtQuick

Singleton {
    readonly property string wallpaper: "/home/nekoconn/.config/hypr/wallpapers/wallpaper2.png"
    readonly property color seed: "#eb3264"
    readonly property bool initialIsDark: true

    readonly property var m3Dark: ({
        primary: "#ffb2bc",
        onPrimary: "#561d28",
        primaryContainer: "#72333e",
        onPrimaryContainer: "#ffd9dd",
        inversePrimary: "#8e4955",
        secondary: "#e5bdc1",
        onSecondary: "#43292d",
        secondaryContainer: "#5c3f43",
        onSecondaryContainer: "#ffd9dd",
        tertiary: "#eabf8f",
        onTertiary: "#452b07",
        tertiaryContainer: "#5e411c",
        onTertiaryContainer: "#ffddb8",
        error: "#ffb4ab",
        onError: "#690005",
        errorContainer: "#93000a",
        onErrorContainer: "#ffdad6",
        background: "#1a1112",
        onBackground: "#f0dedf",
        surface: "#1a1112",
        onSurface: "#f0dedf",
        surfaceDim: "#1a1112",
        surfaceBright: "#413738",
        surfaceContainerLowest: "#140c0d",
        surfaceContainerLow: "#22191a",
        surfaceContainer: "#261d1e",
        surfaceContainerHigh: "#312828",
        surfaceContainerHighest: "#3d3233",
        inverseSurface: "#f0dedf",
        inverseOnSurface: "#382e2f",
        shadow: "#000000",
        scrim: "#000000",
        surfaceVariant: "#524345",
        onSurfaceVariant: "#d7c1c3",
        outline: "#9f8c8e",
        outlineVariant: "#524345",
    })

    readonly property var m3Light: ({
        primary: "#8e4955",
        onPrimary: "#ffffff",
        primaryContainer: "#ffd9dd",
        onPrimaryContainer: "#72333e",
        inversePrimary: "#ffb2bc",
        secondary: "#76565a",
        onSecondary: "#ffffff",
        secondaryContainer: "#ffd9dd",
        onSecondaryContainer: "#5c3f43",
        tertiary: "#785831",
        onTertiary: "#ffffff",
        tertiaryContainer: "#ffddb8",
        onTertiaryContainer: "#5e411c",
        error: "#ba1a1a",
        onError: "#ffffff",
        errorContainer: "#ffdad6",
        onErrorContainer: "#93000a",
        background: "#fff8f7",
        onBackground: "#22191a",
        surface: "#fff8f7",
        onSurface: "#22191a",
        surfaceDim: "#e7d6d7",
        surfaceBright: "#fff8f7",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#fff0f1",
        surfaceContainer: "#fbeaeb",
        surfaceContainerHigh: "#f6e4e5",
        surfaceContainerHighest: "#f0dedf",
        inverseSurface: "#382e2f",
        inverseOnSurface: "#feeded",
        shadow: "#000000",
        scrim: "#000000",
        surfaceVariant: "#f3dddf",
        onSurfaceVariant: "#524345",
        outline: "#847374",
        outlineVariant: "#d7c1c3",
    })

}
