#!/usr/bin/env python3
"""Derive a Material Design 3 colour scheme from a wallpaper, in both dark and
light, and remember which mode each wallpaper was last left in.

One scheme, three outputs, so Hyprland, Quickshell and hyprlock never drift:

    ~/.config/quickshell/Colors.qml   QML singleton  -> Theme.qml (both modes)
    ~/.config/hypr/colors.lua         Lua table      -> hyprland.lua (active mode)
    ~/.config/hypr/colors.conf        hyprlang vars  -> hyprlock.conf, if run manually (active mode)

Usage:
    m3-from-wallpaper.py [wallpaper]             # mode auto-resolved, see below
    m3-from-wallpaper.py [wallpaper] --mode dark # force a mode
    m3-from-wallpaper.py --print                 # show both schemes, write nothing

Mode resolution, when --mode is not given:
    1. this wallpaper's own last-used mode, if it's been seen before
    2. otherwise, the mode the previously-active wallpaper was in
    3. otherwise, dark

That state -- which wallpaper is active, and which mode each one was last
left in -- lives in ~/.config/quickshell/theme-state.json and is updated on
every run, which is what lets Wallpapers.qml's apply() (switching images)
and ThemeMode.qml's toggle() (flipping mode on the current image) share one
code path instead of each tracking it themselves. Both call this script
directly (Quickshell.Io.Process) rather than through a shell wrapper.

The colour science is Google's own: this decodes and downsamples the image
(the one thing Node has no built-in for), then hands the raw pixels to
`mcu/derive.mjs`, a tiny wrapper around the real `@material/material-color-
utilities` package -- the same library behind the actual Material Theme
Builder. Quantization (QuantizerCelebi), seed selection (Score) and the
36-role tonal scheme (SchemeTonalSpot, both light and dark) are all their
code, unmodified.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile

from PIL import Image

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DERIVE_JS = os.path.join(SCRIPT_DIR, "mcu", "derive.mjs")
STATE_PATH = os.path.expanduser("~/.config/quickshell/theme-state.json")

# Role order for the generated files. The values come from derive.mjs now;
# this only fixes the order they're written in.
ROLES = (
    "primary", "onPrimary", "primaryContainer", "onPrimaryContainer", "inversePrimary",
    "secondary", "onSecondary", "secondaryContainer", "onSecondaryContainer",
    "tertiary", "onTertiary", "tertiaryContainer", "onTertiaryContainer",
    "error", "onError", "errorContainer", "onErrorContainer",
    "background", "onBackground", "surface", "onSurface", "surfaceDim", "surfaceBright",
    "surfaceContainerLowest", "surfaceContainerLow", "surfaceContainer",
    "surfaceContainerHigh", "surfaceContainerHighest",
    "inverseSurface", "inverseOnSurface", "shadow", "scrim",
    "surfaceVariant", "onSurfaceVariant", "outline", "outlineVariant",
)


# ------------------------------------------------------------------- state


def load_state():
    try:
        with open(STATE_PATH) as f:
            state = json.load(f)
    except (OSError, json.JSONDecodeError):
        state = {}
    state.setdefault("current_wallpaper", None)
    state.setdefault("modes", {})
    return state


def save_state(state):
    os.makedirs(os.path.dirname(STATE_PATH), exist_ok=True)
    with open(STATE_PATH, "w") as f:
        json.dump(state, f, indent=2)
        f.write("\n")


def resolve_mode(state, wallpaper, explicit_mode):
    if explicit_mode:
        return explicit_mode
    if wallpaper in state["modes"]:
        return state["modes"][wallpaper]
    current = state["current_wallpaper"]
    if current and current in state["modes"]:
        return state["modes"][current]
    return "dark"


# ---------------------------------------------------------------- derive


def derive_schemes(path, sample=256, contrast=0.0):
    """Decode + downsample in Python, derive both schemes via Node."""
    im = Image.open(path).convert("RGB")
    im.thumbnail((sample, sample))
    argb = [(0xFF << 24) | (r << 16) | (g << 8) | b for r, g, b in im.get_flattened_data()]

    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as f:
        json.dump(argb, f)
        pixels_path = f.name

    try:
        result = subprocess.run(
            ["node", DERIVE_JS, pixels_path, str(contrast)],
            capture_output=True, text=True, check=True,
        )
    except FileNotFoundError:
        sys.exit("node not found -- required to run the official colour derivation")
    except subprocess.CalledProcessError as e:
        sys.exit(f"derive.mjs failed:\n{e.stderr}")
    finally:
        os.unlink(pixels_path)

    return json.loads(result.stdout)


# -------------------------------------------------------------------- outputs

BANNER = "Generated by quickshell/scripts/m3-from-wallpaper.py -- do not edit by hand."


def write_qml(path, dark, light, meta, active_mode):
    """Emit both schemes as one map each, not a property each.

    QML reads any property named `on<Capital>` as a signal handler, and half the
    M3 role names start with "on" (onPrimary, onSurfaceVariant, ...). A `var`
    holding a plain object sidesteps that and keeps the role names identical to
    the Lua and hyprlang outputs. Hex strings coerce to `color` on assignment.

    Both modes are included so Quickshell can flip between them live via
    ThemeMode.qml, without waiting on this script or a shell restart --
    `initialIsDark` only seeds that toggle's starting value for a fresh launch.
    """
    lines = [
        f"// {BANNER}",
        f"// Source: {meta['wallpaper']}",
        f"// Seed:   {meta['seed']}  (hue {meta['hue']:.0f}deg, chroma {meta['chroma']:.0f})",
        f"// Derived by: @material/material-color-utilities, SchemeTonalSpot",
        "pragma Singleton",
        "import Quickshell",
        "import QtQuick",
        "",
        "Singleton {",
        f'    readonly property string wallpaper: "{meta["wallpaper"]}"',
        f'    readonly property color seed: "{meta["seed"]}"',
        f"    readonly property bool initialIsDark: {'true' if active_mode == 'dark' else 'false'}",
        "",
    ]
    for name, scheme in (("m3Dark", dark), ("m3Light", light)):
        lines.append(f"    readonly property var {name}: ({{")
        for role in ROLES:
            lines.append(f'        {role}: "{scheme[role]}",')
        lines.append("    })")
        lines.append("")
    lines += ["}", ""]
    open(path, "w").write("\n".join(lines))


def write_lua(path, scheme, meta, active_mode):
    lines = [
        f"-- {BANNER}",
        f"-- Source: {meta['wallpaper']}",
        f"-- Seed:   {meta['seed']}  (hue {meta['hue']:.0f}deg, chroma {meta['chroma']:.0f})",
        f"-- Mode:   {active_mode}",
        "-- Values are Hyprland colour literals; `.hex` holds the bare hex digits.",
        "",
        "return {",
    ]
    for role in ROLES:
        lines.append(f'    {role} = "rgb({scheme[role].lstrip("#")})",')
    lines.append("    hex = {")
    for role in ROLES:
        lines.append(f'        {role} = "{scheme[role].lstrip("#")}",')
    lines += ["    },", "}", ""]
    open(path, "w").write("\n".join(lines))


def write_conf(path, scheme, meta, active_mode):
    lines = [
        f"# {BANNER}",
        f"# Source: {meta['wallpaper']}",
        f"# Mode:   {active_mode}",
        "# $role is a colour literal; $roleHex is bare digits, for pango markup.",
        "",
    ]
    for role in ROLES:
        hexval = scheme[role].lstrip("#")
        lines.append(f"${role} = rgb({hexval})")
        lines.append(f"${role}Hex = {hexval}")
    open(path, "w").write("\n".join(lines) + "\n")


def wallpaper_from_static_config():
    # hyprpaper.conf's own path -- there's no live daemon to ask instead
    # since Wallpaper.qml renders the background directly now, but the file
    # is still a reasonable static default for a machine that's never run
    # this script and so has no theme-state.json yet.
    conf = os.path.expanduser("~/.config/hypr/hyprpaper.conf")
    try:
        m = re.search(r"^\s*path\s*=\s*(.+?)\s*$", open(conf).read(), re.M)
    except OSError:
        return None
    return os.path.expanduser(m.group(1)) if m else None


def main():
    ap = argparse.ArgumentParser(description="Derive light+dark M3 colour schemes from a wallpaper.")
    ap.add_argument("wallpaper", nargs="?", help="image to sample (default: from hyprpaper.conf)")
    ap.add_argument("--mode", choices=("dark", "light"),
                     help="force a mode instead of auto-resolving from theme-state.json")
    ap.add_argument("--contrast", type=float, default=0.0,
                     help="SchemeTonalSpot contrastLevel, -1..1 (default 0, spec standard)")
    ap.add_argument("--print", dest="dry", action="store_true", help="print both schemes, write nothing")
    args = ap.parse_args()

    # State's own record of "the active wallpaper" beats the static
    # hyprpaper.conf, which nothing keeps in sync any more (Wallpaper.qml
    # renders the background directly; hyprpaper isn't even running). It
    # only matters as a last-resort fallback, for a machine that has never
    # run this script.
    state = load_state()
    path = args.wallpaper or state["current_wallpaper"] or wallpaper_from_static_config()
    if not path or not os.path.exists(path):
        sys.exit(f"wallpaper not found: {path!r}")
    path = os.path.realpath(path)

    derived = derive_schemes(path, contrast=args.contrast)
    dark, light = derived["dark"], derived["light"]
    meta = {"wallpaper": path, "seed": derived["seed"], "hue": derived["hue"], "chroma": derived["chroma"]}

    mode = resolve_mode(state, path, args.mode)
    active = dark if mode == "dark" else light

    if args.dry:
        print(f"wallpaper : {path}")
        print(f"seed      : {meta['seed']}  hue {meta['hue']:.0f}deg  chroma {meta['chroma']:.0f}")
        print(f"mode      : {mode}  (resolved; pass --mode to override)")
        for label, scheme in (("dark", dark), ("light", light)):
            print(f"-- {label} --")
            for role in ROLES:
                print(f"  {role:<24} {scheme[role]}")
        return

    home = os.path.expanduser("~")
    write_qml(f"{home}/.config/quickshell/Colors.qml", dark, light, meta, mode)
    write_lua(f"{home}/.config/hypr/colors.lua", active, meta, mode)
    write_conf(f"{home}/.config/hypr/colors.conf", active, meta, mode)

    state["current_wallpaper"] = path
    state["modes"][path] = mode
    save_state(state)

    print(f"seed {meta['seed']} (hue {meta['hue']:.0f}deg, chroma {meta['chroma']:.0f}) "
          f"from {os.path.basename(path)}, mode={mode}")
    print("wrote quickshell/Colors.qml, hypr/colors.lua, hypr/colors.conf, hypr/theme-state.json")


if __name__ == "__main__":
    main()
