#!/usr/bin/env python3
"""Vendors a fixed set of Material Symbols (rounded, weight 400) glyphs into
quickshell/Icons.qml as inline SVG strings, so the bar's icons render as real
vector art instead of mixed Nerd Font glyphs (which don't share one drawing
canvas, so unrelated glyphs land at different optical sizes at the same
font-size -- see the muted-volume icon issue this replaces).

Source package: @material-symbols/svg-400 (npm). Re-run after `npm install
@material-symbols/svg-400` in a scratch directory if the icon list below
changes; nothing at runtime depends on npm or node_modules.
"""
import re
import sys

SRC_DIR = sys.argv[1] if len(sys.argv) > 1 else None
if not SRC_DIR:
    print("usage: vendor-material-icons.py <path to @material-symbols/svg-400/rounded>")
    sys.exit(1)

OUT_PATH = "/home/nekoconn/.config/quickshell/Icons.qml"

# name -> filename (without .svg) in the rounded/ directory.
ICONS = {
    "cpu": "developer_board",
    "memory": "memory",
    "keyboard": "keyboard",
    # The "language_X" family is Material Symbols' own keyboard-layout
    # glyph set -- a short text abbreviation per layout (US, kana for
    # Japanese romaji/kana input, ...), not a flag. There's no Vietnamese
    # entry in it; keyboard_vn uses the family's generic "INTL" glyph
    # instead of a language-specific one.
    "keyboard_us": "language_us",
    "keyboard_jp": "language_japanese_kana",
    "keyboard_vn": "language_international",
    "brightness": "light_mode",

    "volume_high": "volume_up",
    "volume_medium": "volume_down",
    "volume_low": "volume_mute",
    "volume_muted": "volume_off",

    "battery_0": "battery_0_bar",
    "battery_1": "battery_1_bar",
    "battery_2": "battery_2_bar",
    "battery_3": "battery_3_bar",
    "battery_4": "battery_4_bar",
    "battery_5": "battery_5_bar",
    "battery_6": "battery_6_bar",
    "battery_full": "battery_full",
    "battery_charging_20": "battery_charging_20",
    "battery_charging_30": "battery_charging_30",
    "battery_charging_50": "battery_charging_50",
    "battery_charging_60": "battery_charging_60",
    "battery_charging_80": "battery_charging_80",
    "battery_charging_90": "battery_charging_90",
    "battery_charging_full": "battery_charging_full",

    "bluetooth_on": "bluetooth",
    "bluetooth_off": "bluetooth_disabled",
    "bluetooth_connected": "bluetooth_connected",

    # The "wifi" family, not "network_wifi" -- tops out at 2 bars plus full
    # rather than 3 plus full, so Network.qml's tiering has one fewer step.
    "wifi_off": "wifi_off",
    "wifi_low": "wifi_1_bar",
    "wifi_medium": "wifi_2_bar",
    "wifi_high": "wifi",

    "media_stopped": "stop",
    "media_playing": "play_arrow",
    "media_paused": "pause",

    "notification": "notifications",

    # Overlay.qml's menus (power/screenshot/commands) and the launcher/search
    # -- previously Nerd Font glyphs, which don't share a drawing canvas or
    # optical weight with these, so they never quite matched size-for-size.
    "lock": "lock",
    "reboot": "restart_alt",
    "shutdown": "power_settings_new",
    "boot_vm": "desktop_windows",
    "screenshot_desktop": "monitor",
    "screenshot_area": "crop",
    "screenshot_window": "select_window",
    "wallpaper": "image",
    "theme_dark": "dark_mode",
    "theme_light": "light_mode",
    "app_generic": "apps",
    "search": "search",
}


def load(name: str) -> str:
    with open(f"{SRC_DIR}/{name}.svg") as f:
        svg = f.read()
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    svg = re.sub(r'\s(width|height)="[^"]*"', "", svg)
    svg = svg.strip()
    # Material Symbols' source sets no fill at all -- SVG then defaults to
    # solid black, not transparent/inherit -- so SvgIcon's recolor always has
    # an attribute to overwrite regardless of which icon this is.
    if 'fill="' not in svg.split(">", 1)[0]:
        svg = svg.replace("<svg ", '<svg fill="#000000" ', 1)
    # One line, and quote-safe for embedding in a QML double-quoted string.
    svg = " ".join(svg.split())
    svg = svg.replace('"', '\\"')
    return svg


entries = []
for key, fname in ICONS.items():
    entries.append(f'        {key}: "{load(fname)}"')
entries_block = ",\n".join(entries)

qml = f'''// Generated by quickshell/scripts/vendor-material-icons.py -- do not edit by
// hand. Material Symbols (rounded, weight 400), Apache-2.0.
// Source: @material-symbols/svg-400 (npm).
pragma Singleton
import Quickshell

Singleton {{
    readonly property var svg: ({{
{entries_block}
    }})
}}
'''

with open(OUT_PATH, "w") as f:
    f.write(qml)

print(f"wrote {OUT_PATH} ({len(ICONS)} icons, {len(qml)} bytes)")
